using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEditor;
using UnityEngine.UI;
using System.Text.RegularExpressions;

public class Variants : MonoBehaviour
{
    [Header("Sprites")]
    [SerializeField] private Sprite spriteBlack;
    [SerializeField] private Sprite spriteWhite;
    [SerializeField] private Sprite spriteBrown;
    [SerializeField] private Sprite spriteOrange;
    [SerializeField] private Sprite spriteYellow;
    [SerializeField] private Sprite spriteRed;
    [SerializeField] private Sprite spriteGreen;
    [SerializeField] private Sprite spriteBlue;
    [SerializeField] private Sprite spritePurple;
    [SerializeField] private Sprite spritePink;

    [Header("Orange Modifications")]
    [SerializeField] private string roleNameOrange = "Carrier";
    [SerializeField] private float flatHPOrange = 0f;
    [SerializeField] private float percentageHPOrange = 0.3f;
    [SerializeField] private float flatArmorOrange = -15f;
    [SerializeField] private float percentageArmorOrange = -0.15f;
    [SerializeField] private float flatMoveSpeedOrange = 0f;
    [SerializeField] private float percentageMoveSpeedOrange = 0.05f;
    [SerializeField] private float flatResistanceOrange = -10f;
    [SerializeField] private float percentageResistanceOrange = -0.1f;
    [SerializeField] private float flatDodgeOrange = -10f;
    [SerializeField] private float percentageDodgeOrange = -0.1f;
    [SerializeField] private float flatCarryCapacityOrange = 0f;
    [SerializeField] private float percentageCarryCapacityOrange = 0.5f;
    [SerializeField] private float flatShieldOrange = 0f;
    [SerializeField] private float percentageShieldOrange = 0f;
    [SerializeField] private bool stealHoneyOrange = true;
    [SerializeField] private float percentageActionPowerOrange = 0f;
    [SerializeField] private float percentageEffectPowerOrange = 0f;
    [SerializeField] private float percentagePassivePowerOrange = 0f;
    [SerializeField] private string extraActionOrange;
    [SerializeField] private GameObject actionPrefabOrange;
    [SerializeField] private SoundType[] actionSoundOrange;
    [SerializeField] private float actionPowerModifierOrange = 0f;
    [SerializeField] private float actionRateModifierOrange = 0f;
    [SerializeField] private float actionRangeModifierOrange = 0f;
    [SerializeField] private float actionPierceModifierOrange = 0f;
    [SerializeField] private float actionDurationOrange = 0f;
    [SerializeField] private float actionExtraModifierOrange = 0f;
    [SerializeField] private string extraEffectOrange;
    [SerializeField] private GameObject effectPrefabOrange;
    [SerializeField] private SoundType[] effectSoundOrange;
    [SerializeField] private float effectPowerModifierOrange = 0f;
    [SerializeField] private float effectRateModifierOrange = 0f;
    [SerializeField] private float effectRangeModifierOrange = 0f;
    [SerializeField] private float effectPierceModifierOrange = 0f;
    [SerializeField] private float effectDurationOrange = 0f;
    [SerializeField] private float effectExtraModifierOrange = 0f;
    [SerializeField] private string extraPassiveOrange;
    [SerializeField] private GameObject passivePrefabOrange;
    [SerializeField] private SoundType[] passiveSoundOrange;
    [SerializeField] private float passivePowerModifierOrange = 0f;
    [SerializeField] private float passiveRateModifierOrange = 0f;
    [SerializeField] private float passiveRangeModifierOrange = 0f;
    [SerializeField] private float passivePierceModifierOrange = 0f;
    [SerializeField] private float passiveDurationOrange = 0f;
    [SerializeField] private float passiveExtraModifierOrange = 0f;

    [Header("Brown Modifications")]
    [SerializeField] private string roleNameBrown = "Hauler";
    [SerializeField] private float flatHPBrown = 0f;
    [SerializeField] private float percentageHPBrown = 0.6f;
    [SerializeField] private float flatArmorBrown = 20f;
    [SerializeField] private float percentageArmorBrown = 0.2f;
    [SerializeField] private float flatMoveSpeedBrown = 0f;
    [SerializeField] private float percentageMoveSpeedBrown = -0.25f;
    [SerializeField] private float flatResistanceBrown = 10f;
    [SerializeField] private float percentageResistanceBrown = 0.1f;
    [SerializeField] private float flatDodgeBrown = -20f;
    [SerializeField] private float percentageDodgeBrown = -0.2f;
    [SerializeField] private float flatCarryCapacityBrown = 0f;
    [SerializeField] private float percentageCarryCapacityBrown = 1f;
    [SerializeField] private float flatShieldBrown = 0f;
    [SerializeField] private float percentageShieldBrown = 0f;
    [SerializeField] private bool stealHoneyBrown = true;
    [SerializeField] private float percentageActionPowerBrown = 0f;
    [SerializeField] private float percentageEffectPowerBrown = 0f;
    [SerializeField] private float percentagePassivePowerBrown = 0f;
    [SerializeField] private string extraActionBrown;
    [SerializeField] private GameObject actionPrefabBrown;
    [SerializeField] private SoundType[] actionSoundBrown;
    [SerializeField] private float actionPowerModifierBrown = 0f;
    [SerializeField] private float actionRateModifierBrown = 0f;
    [SerializeField] private float actionRangeModifierBrown = 0f;
    [SerializeField] private float actionPierceModifierBrown = 0f;
    [SerializeField] private float actionDurationBrown = 0f;
    [SerializeField] private float actionExtraModifierBrown = 0f;
    [SerializeField] private string extraEffectBrown;
    [SerializeField] private GameObject effectPrefabBrown;
    [SerializeField] private SoundType[] effectSoundBrown;
    [SerializeField] private float effectPowerModifierBrown = 0f;
    [SerializeField] private float effectRateModifierBrown = 0f;
    [SerializeField] private float effectRangeModifierBrown = 0f;
    [SerializeField] private float effectPierceModifierBrown = 0f;
    [SerializeField] private float effectDurationBrown = 0f;
    [SerializeField] private float effectExtraModifierBrown = 0f;
    [SerializeField] private string extraPassiveBrown;
    [SerializeField] private GameObject passivePrefabBrown;
    [SerializeField] private SoundType[] passiveSoundBrown;
    [SerializeField] private float passivePowerModifierBrown = 0f;
    [SerializeField] private float passiveRateModifierBrown = 0f;
    [SerializeField] private float passiveRangeModifierBrown = 0f;
    [SerializeField] private float passivePierceModifierBrown = 0f;
    [SerializeField] private float passiveDurationBrown = 0f;
    [SerializeField] private float passiveExtraModifierBrown = 0f;
    
    [Header("Green Modifications")]
    [SerializeField] private string roleNameGreen = "Regenerator";
    [SerializeField] private float flatHPGreen = 0f;
    [SerializeField] private float percentageHPGreen = 0.35f;
    [SerializeField] private float flatArmorGreen = 0f;
    [SerializeField] private float percentageArmorGreen = 0f;
    [SerializeField] private float flatMoveSpeedGreen = 0f;
    [SerializeField] private float percentageMoveSpeedGreen = -0.15f;
    [SerializeField] private float flatResistanceGreen = 25f;
    [SerializeField] private float percentageResistanceGreen = 0.25f;
    [SerializeField] private float flatDodgeGreen = -10f;
    [SerializeField] private float percentageDodgeGreen = -0.1f;
    [SerializeField] private float flatCarryCapacityGreen = 0f;
    [SerializeField] private float percentageCarryCapacityGreen = 0.2f;
    [SerializeField] private float flatShieldGreen = 0f;
    [SerializeField] private float percentageShieldGreen = 0f;
    [SerializeField] private bool stealHoneyGreen = true;
    [SerializeField] private float percentageActionPowerGreen = 0f;
    [SerializeField] private float percentageEffectPowerGreen = 0f;
    [SerializeField] private float percentagePassivePowerGreen = 0f;
    [SerializeField] private string extraActionGreen;
    [SerializeField] private GameObject actionPrefabGreen;
    [SerializeField] private SoundType[] actionSoundGreen;
    [SerializeField] private float actionPowerModifierGreen = 0f;
    [SerializeField] private float actionRateModifierGreen = 0f;
    [SerializeField] private float actionRangeModifierGreen = 0f;
    [SerializeField] private float actionPierceModifierGreen = 0f;
    [SerializeField] private float actionDurationGreen = 0f;
    [SerializeField] private float actionExtraModifierGreen = 0f;
    [SerializeField] private string extraEffectGreen = "Health Regen";
    [SerializeField] private GameObject effectPrefabGreen;
    [SerializeField] private SoundType[] effectSoundGreen;
    [SerializeField] private float effectPowerModifierGreen = 0f;
    [SerializeField] private float effectRateModifierGreen = 1f;
    [SerializeField] private float effectRangeModifierGreen = 1f;
    [SerializeField] private float effectPierceModifierGreen = 1f;
    [SerializeField] private float effectDurationGreen = 1f;
    [SerializeField] private float effectExtraModifierGreen = 0.02f;
    [SerializeField] private string extraPassiveGreen;
    [SerializeField] private GameObject passivePrefabGreen;
    [SerializeField] private SoundType[] passiveSoundGreen;
    [SerializeField] private float passivePowerModifierGreen = 0f;
    [SerializeField] private float passiveRateModifierGreen = 0f;
    [SerializeField] private float passiveRangeModifierGreen = 0f;
    [SerializeField] private float passivePierceModifierGreen = 0f;
    [SerializeField] private float passiveDurationGreen = 0f;
    [SerializeField] private float passiveExtraModifierGreen = 0f;
    
    [Header("Blue Modifications")]
    [SerializeField] private string roleNameBlue = "Sentinel";
    [SerializeField] private float flatHPBlue = 0f;
    [SerializeField] private float percentageHPBlue = 0.25f;
    [SerializeField] private float flatArmorBlue = 40f;
    [SerializeField] private float percentageArmorBlue = 0.4f;
    [SerializeField] private float flatMoveSpeedBlue = 0f;
    [SerializeField] private float percentageMoveSpeedBlue = -0.2f;
    [SerializeField] private float flatResistanceBlue = 30f;
    [SerializeField] private float percentageResistanceBlue = -0.3f;
    [SerializeField] private float flatDodgeBlue = -20f;
    [SerializeField] private float percentageDodgeBlue = -0.2f;
    [SerializeField] private float flatCarryCapacityBlue = 0f;
    [SerializeField] private float percentageCarryCapacityBlue = 0f;
    [SerializeField] private float flatShieldBlue = 0f;
    [SerializeField] private float percentageShieldBlue = 0f;
    [SerializeField] private bool stealHoneyBlue = false;
    [SerializeField] private float percentageActionPowerBlue = 0f;
    [SerializeField] private float percentageEffectPowerBlue = 0f;
    [SerializeField] private float percentagePassivePowerBlue = 0f;
    [SerializeField] private string extraActionBlue;
    [SerializeField] private GameObject actionPrefabBlue;
    [SerializeField] private SoundType[] actionSoundBlue;
    [SerializeField] private float actionPowerModifierBlue = 0f;
    [SerializeField] private float actionRateModifierBlue = 0f;
    [SerializeField] private float actionRangeModifierBlue = 0f;
    [SerializeField] private float actionPierceModifierBlue = 0f;
    [SerializeField] private float actionDurationBlue = 0f;
    [SerializeField] private float actionExtraModifierBlue = 0f;
    [SerializeField] private string extraEffectBlue;
    [SerializeField] private GameObject effectPrefabBlue;
    [SerializeField] private SoundType[] effectSoundBlue;
    [SerializeField] private float effectPowerModifierBlue = 0f;
    [SerializeField] private float effectRateModifierBlue = 0f;
    [SerializeField] private float effectRangeModifierBlue = 0f;
    [SerializeField] private float effectPierceModifierBlue = 0f;
    [SerializeField] private float effectDurationBlue = 0f;
    [SerializeField] private float effectExtraModifierBlue = 0f;
    [SerializeField] private string extraPassiveBlue;
    [SerializeField] private GameObject passivePrefabBlue;
    [SerializeField] private SoundType[] passiveSoundBlue;
    [SerializeField] private float passivePowerModifierBlue = 0f;
    [SerializeField] private float passiveRateModifierBlue = 0f;
    [SerializeField] private float passiveRangeModifierBlue = 0f;
    [SerializeField] private float passivePierceModifierBlue = 0f;
    [SerializeField] private float passiveDurationBlue = 0f;
    [SerializeField] private float passiveExtraModifierBlue = 0f;
    
    [Header("Yellow Modifications")]
    [SerializeField] private string roleNameYellow = "Scout";
    [SerializeField] private float flatHPYellow = 0f;
    [SerializeField] private float percentageHPYellow = -0.15f;
    [SerializeField] private float flatArmorYellow = -20f;
    [SerializeField] private float percentageArmorYellow = -0.2f;
    [SerializeField] private float flatMoveSpeedYellow = 0f;
    [SerializeField] private float percentageMoveSpeedYellow = 0.5f;
    [SerializeField] private float flatResistanceYellow = -10f;
    [SerializeField] private float percentageResistanceYellow = -0.1f;
    [SerializeField] private float flatDodgeYellow = 30f;
    [SerializeField] private float percentageDodgeYellow = 0.3f;
    [SerializeField] private float flatCarryCapacityYellow = 0f;
    [SerializeField] private float percentageCarryCapacityYellow = -0.25f;
    [SerializeField] private float flatShieldYellow = 0f;
    [SerializeField] private float percentageShieldYellow = 0f;
    [SerializeField] private bool stealHoneyYellow = true;
    [SerializeField] private float percentageActionPowerYellow = 0f;
    [SerializeField] private float percentageEffectPowerYellow = 0f;
    [SerializeField] private float percentagePassivePowerYellow = 0f;
    [SerializeField] private string extraActionYellow;
    [SerializeField] private GameObject actionPrefabYellow;
    [SerializeField] private SoundType[] actionSoundYellow;
    [SerializeField] private float actionPowerModifierYellow = 0f;
    [SerializeField] private float actionRateModifierYellow = 0f;
    [SerializeField] private float actionRangeModifierYellow = 0f;
    [SerializeField] private float actionPierceModifierYellow = 0f;
    [SerializeField] private float actionDurationYellow = 0f;
    [SerializeField] private float actionExtraModifierYellow = 0f;
    [SerializeField] private string extraEffectYellow;
    [SerializeField] private GameObject effectPrefabYellow;
    [SerializeField] private SoundType[] effectSoundYellow;
    [SerializeField] private float effectPowerModifierYellow = 0f;
    [SerializeField] private float effectRateModifierYellow = 0f;
    [SerializeField] private float effectRangeModifierYellow = 0f;
    [SerializeField] private float effectPierceModifierYellow = 0f;
    [SerializeField] private float effectDurationYellow = 0f;
    [SerializeField] private float effectExtraModifierYellow = 0f;
    [SerializeField] private string extraPassiveYellow;
    [SerializeField] private GameObject passivePrefabYellow;
    [SerializeField] private SoundType[] passiveSoundYellow;
    [SerializeField] private float passivePowerModifierYellow = 0f;
    [SerializeField] private float passiveRateModifierYellow = 0f;
    [SerializeField] private float passiveRangeModifierYellow = 0f;
    [SerializeField] private float passivePierceModifierYellow = 0f;
    [SerializeField] private float passiveDurationYellow = 0f;
    [SerializeField] private float passiveExtraModifierYellow = 0f;
    
    [Header("Red Modifications")]
    [SerializeField] private string roleNameRed = "Brawler";
    [SerializeField] private float flatHPRed = 0f;
    [SerializeField] private float percentageHPRed = 0.2f;
    [SerializeField] private float flatArmorRed = 0f;
    [SerializeField] private float percentageArmorRed = 0f;
    [SerializeField] private float flatMoveSpeedRed = 0f;
    [SerializeField] private float percentageMoveSpeedRed = 0.3f;
    [SerializeField] private float flatResistanceRed = -15f;
    [SerializeField] private float percentageResistanceRed = -0.15f;
    [SerializeField] private float flatDodgeRed = 5f;
    [SerializeField] private float percentageDodgeRed = 0.05f;
    [SerializeField] private float flatCarryCapacityRed = 0f;
    [SerializeField] private float percentageCarryCapacityRed = 0f;
    [SerializeField] private float flatShieldRed = 0f;
    [SerializeField] private float percentageShieldRed = 0f;
    [SerializeField] private bool stealHoneyRed = false;
    [SerializeField] private float percentageActionPowerRed = 0f;
    [SerializeField] private float percentageEffectPowerRed = 0f;
    [SerializeField] private float percentagePassivePowerRed = 0f;
    [SerializeField] private string extraActionRed;
    [SerializeField] private GameObject actionPrefabRed;
    [SerializeField] private SoundType[] actionSoundRed;
    [SerializeField] private float actionPowerModifierRed = 0f;
    [SerializeField] private float actionRateModifierRed = 0f;
    [SerializeField] private float actionRangeModifierRed = 0f;
    [SerializeField] private float actionPierceModifierRed = 0f;
    [SerializeField] private float actionDurationRed = 0f;
    [SerializeField] private float actionExtraModifierRed = 0f;
    [SerializeField] private string extraEffectRed;
    [SerializeField] private GameObject effectPrefabRed;
    [SerializeField] private SoundType[] effectSoundRed;
    [SerializeField] private float effectPowerModifierRed = 0f;
    [SerializeField] private float effectRateModifierRed = 0f;
    [SerializeField] private float effectRangeModifierRed = 0f;
    [SerializeField] private float effectPierceModifierRed = 0f;
    [SerializeField] private float effectDurationRed = 0f;
    [SerializeField] private float effectExtraModifierRed = 0f;
    [SerializeField] private string extraPassiveRed;
    [SerializeField] private GameObject passivePrefabRed;
    [SerializeField] private SoundType[] passiveSoundRed;
    [SerializeField] private float passivePowerModifierRed = 0f;
    [SerializeField] private float passiveRateModifierRed = 0f;
    [SerializeField] private float passiveRangeModifierRed = 0f;
    [SerializeField] private float passivePierceModifierRed = 0f;
    [SerializeField] private float passiveDurationRed = 0f;
    [SerializeField] private float passiveExtraModifierRed = 0f;
    
    [Header("Black Modifications")]
    [SerializeField] private string roleNameBlack = "Predator;
    [SerializeField] private float flatHPBlack = 0f;
    [SerializeField] private float percentageHPBlack = -0.2f;
    [SerializeField] private float flatArmorBlack = -10f;
    [SerializeField] private float percentageArmorBlack = -0.1f;
    [SerializeField] private float flatMoveSpeedBlack = 0f;
    [SerializeField] private float percentageMoveSpeedBlack = 0.5f;
    [SerializeField] private float flatResistanceBlack = 0f;
    [SerializeField] private float percentageResistanceBlack = 0f;
    [SerializeField] private float flatDodgeBlack = 20f;
    [SerializeField] private float percentageDodgeBlack = 0.2f;
    [SerializeField] private float flatCarryCapacityBlack = 0f;
    [SerializeField] private float percentageCarryCapacityBlack = 0f;
    [SerializeField] private float flatShieldBlack = 0f;
    [SerializeField] private float percentageShieldBlack = 0f;
    [SerializeField] private bool stealHoneyBlack = false;
    [SerializeField] private float percentageActionPowerBlack = 0f;
    [SerializeField] private float percentageEffectPowerBlack = 0f;
    [SerializeField] private float percentagePassivePowerBlack = 0f;
    [SerializeField] private string extraActionBlack;
    [SerializeField] private GameObject actionPrefabBlack;
    [SerializeField] private SoundType[] actionSoundBlack;
    [SerializeField] private float actionPowerModifierBlack = 0f;
    [SerializeField] private float actionRateModifierBlack = 0f;
    [SerializeField] private float actionRangeModifierBlack = 0f;
    [SerializeField] private float actionPierceModifierBlack = 0f;
    [SerializeField] private float actionDurationBlack = 0f;
    [SerializeField] private float actionExtraModifierBlack = 0f;
    [SerializeField] private string extraEffectBlack;
    [SerializeField] private GameObject effectPrefabBlack;
    [SerializeField] private SoundType[] effectSoundBlack;
    [SerializeField] private float effectPowerModifierBlack = 0f;
    [SerializeField] private float effectRateModifierBlack = 0f;
    [SerializeField] private float effectRangeModifierBlack = 0f;
    [SerializeField] private float effectPierceModifierBlack = 0f;
    [SerializeField] private float effectDurationBlack = 0f;
    [SerializeField] private float effectExtraModifierBlack = 0f;
    [SerializeField] private string extraPassiveBlack;
    [SerializeField] private GameObject passivePrefabBlack;
    [SerializeField] private SoundType[] passiveSoundBlack;
    [SerializeField] private float passivePowerModifierBlack = 0f;
    [SerializeField] private float passiveRateModifierBlack = 0f;
    [SerializeField] private float passiveRangeModifierBlack = 0f;
    [SerializeField] private float passivePierceModifierBlack = 0f;
    [SerializeField] private float passiveDurationBlack = 0f;
    [SerializeField] private float passiveExtraModifierBlack = 0f;
    
    [Header("White Modifications")]
    [SerializeField] private string roleNameWhite = "Shielder";
    [SerializeField] private float flatHPWhite = 0f;
    [SerializeField] private float percentageHPWhite = 0.2f;
    [SerializeField] private float flatArmorWhite =20f;
    [SerializeField] private float percentageArmorWhite = 0.2f;
    [SerializeField] private float flatMoveSpeedWhite = 0f;
    [SerializeField] private float percentageMoveSpeedWhite = -0.1f;
    [SerializeField] private float flatResistanceWhite = 20f;
    [SerializeField] private float percentageResistanceWhite = 0.2f;
    [SerializeField] private float flatDodgeWhite = 0f;
    [SerializeField] private float percentageDodgeWhite = 0f;
    [SerializeField] private float flatCarryCapacityWhite = 0f;
    [SerializeField] private float percentageCarryCapacityWhite = 0f;
    [SerializeField] private float flatShieldWhite = 0f;
    [SerializeField] private float percentageShieldWhite = 0f;
    [SerializeField] private bool stealHoneyWhite = true;
    [SerializeField] private float percentageActionPowerWhite = 0f;
    [SerializeField] private float percentageEffectPowerWhite = 0f;
    [SerializeField] private float percentagePassivePowerWhite = 0f;
    [SerializeField] private string extraActionWhite;
    [SerializeField] private GameObject actionPrefabWhite;
    [SerializeField] private SoundType[] actionSoundWhite;
    [SerializeField] private float actionPowerModifierWhite = 0f;
    [SerializeField] private float actionRateModifierWhite = 0f;
    [SerializeField] private float actionRangeModifierWhite = 0f;
    [SerializeField] private float actionPierceModifierWhite = 0f;
    [SerializeField] private float actionDurationWhite = 0f;
    [SerializeField] private float actionExtraModifierWhite = 0f;
    [SerializeField] private string extraEffectWhite = "Shield";
    [SerializeField] private GameObject effectPrefabWhite;
    [SerializeField] private SoundType[] effectSoundWhite;
    [SerializeField] private float effectPowerModifierWhite = 0.02f;
    [SerializeField] private float effectRateModifierWhite = 1f;
    [SerializeField] private float effectRangeModifierWhite = 1f;
    [SerializeField] private float effectPierceModifierWhite = 1f;
    [SerializeField] private float effectDurationWhite = 0f;
    [SerializeField] private float effectExtraModifierWhite = 0.25f;
    [SerializeField] private string extraPassiveWhite;
    [SerializeField] private GameObject passivePrefabWhite;
    [SerializeField] private SoundType[] passiveSoundWhite;
    [SerializeField] private float passivePowerModifierWhite = 0f;
    [SerializeField] private float passiveRateModifierWhite = 0f;
    [SerializeField] private float passiveRangeModifierWhite = 0f;
    [SerializeField] private float passivePierceModifierWhite = 0f;
    [SerializeField] private float passiveDurationWhite = 0f;
    [SerializeField] private float passiveExtraModifierWhite = 0f;
    
    [Header("Purple Modifications")]
    [SerializeField] private string roleNamePurple = "Trickster";
    [SerializeField] private float flatHPPurple = 0f;
    [SerializeField] private float percentageHPPurple = -0.2f;
    [SerializeField] private float flatArmorPurple = 0f;
    [SerializeField] private float percentageArmorPurple = 0f;
    [SerializeField] private float flatMoveSpeedPurple = 0f;
    [SerializeField] private float percentageMoveSpeedPurple = 0.1f;
    [SerializeField] private float flatResistancePurple = 10f;
    [SerializeField] private float percentageResistancePurple = 0.1f;
    [SerializeField] private float flatDodgePurple = 25f;
    [SerializeField] private float percentageDodgePurple = 0.25f;
    [SerializeField] private float flatCarryCapacityPurple = 0f;
    [SerializeField] private float percentageCarryCapacityPurple = 0f;
    [SerializeField] private float flatShieldPurple = 0f;
    [SerializeField] private float percentageShieldPurple = 0f;
    [SerializeField] private bool stealHoneyPurple = true;
    [SerializeField] private float percentageActionPowerPurple = 0f;
    [SerializeField] private float percentageEffectPowerPurple = 0f;
    [SerializeField] private float percentagePassivePowerPurple = 0f;
    [SerializeField] private string extraActionPurple;
    [SerializeField] private GameObject actionPrefabPurple;
    [SerializeField] private SoundType[] actionSoundPurple;
    [SerializeField] private float actionPowerModifierPurple = 0f;
    [SerializeField] private float actionRateModifierPurple = 0f;
    [SerializeField] private float actionRangeModifierPurple = 0f;
    [SerializeField] private float actionPierceModifierPurple = 0f;
    [SerializeField] private float actionDurationPurple = 0f;
    [SerializeField] private float actionExtraModifierPurple = 0f;
    [SerializeField] private string extraEffectPurple = "Stealth";
    [SerializeField] private GameObject effectPrefabPurple;
    [SerializeField] private SoundType[] effectSoundPurple;
    [SerializeField] private float effectPowerModifierPurple = 0.25f;
    [SerializeField] private float effectRateModifierPurple = 0.125f;
    [SerializeField] private float effectRangeModifierPurple = 0f;
    [SerializeField] private float effectPierceModifierPurple = 0f;
    [SerializeField] private float effectDurationPurple = 5f;
    [SerializeField] private float effectExtraModifierPurple = 0f;
    [SerializeField] private string extraPassivePurple;
    [SerializeField] private GameObject passivePrefabPurple;
    [SerializeField] private SoundType[] passiveSoundPurple;
    [SerializeField] private float passivePowerModifierPurple = 0f;
    [SerializeField] private float passiveRateModifierPurple = 0f;
    [SerializeField] private float passiveRangeModifierPurple = 0f;
    [SerializeField] private float passivePierceModifierPurple = 0f;
    [SerializeField] private float passiveDurationPurple = 0f;
    [SerializeField] private float passiveExtraModifierPurple = 0f;
    
    [Header("Pink Modifications")]
    [SerializeField] private string roleNamePink = "Debilitator";
    [SerializeField] private float flatHPPink = 0f;
    [SerializeField] private float percentageHPPink = -0.2f;
    [SerializeField] private float flatArmorPink = -10f;
    [SerializeField] private float percentageArmorPink = -0.1f;
    [SerializeField] private float flatMoveSpeedPink = 0f;
    [SerializeField] private float percentageMoveSpeedPink = -0.05f;
    [SerializeField] private float flatResistancePink = 15f;
    [SerializeField] private float percentageResistancePink = 0.15f;
    [SerializeField] private float flatDodgePink = 0f;
    [SerializeField] private float percentageDodgePink = 0f;
    [SerializeField] private float flatCarryCapacityPink = 0f;
    [SerializeField] private float percentageCarryCapacityPink = 0.25f;
    [SerializeField] private float flatShieldPink = 0f;
    [SerializeField] private float percentageShieldPink = 0f;
    [SerializeField] private bool stealHoneyPink = true;
    [SerializeField] private float percentageActionPowerPink = 0f;
    [SerializeField] private float percentageEffectPowerPink = 0f;
    [SerializeField] private float percentagePassivePowerPink = 0f;
    [SerializeField] private string extraActionPink;
    [SerializeField] private GameObject actionPrefabPink;
    [SerializeField] private SoundType[] actionSoundPink;
    [SerializeField] private float actionPowerModifierPink = 0f;
    [SerializeField] private float actionRateModifierPink = 0f;
    [SerializeField] private float actionRangeModifierPink = 0f;
    [SerializeField] private float actionPierceModifierPink = 0f;
    [SerializeField] private float actionDurationPink = 0f;
    [SerializeField] private float actionExtraModifierPink = 0f;
    [SerializeField] private string extraEffectPink = "Debilitate";
    [SerializeField] private GameObject effectPrefabPink;
    [SerializeField] private SoundType[] effectSoundPink;
    [SerializeField] private float effectPowerModifierPink = 1f;
    [SerializeField] private float effectRateModifierPink = 1f;
    [SerializeField] private float effectRangeModifierPink = 5f;
    [SerializeField] private float effectPierceModifierPink = 0f;
    [SerializeField] private float effectDurationPink = 1f;
    [SerializeField] private float effectExtraModifierPink = 0f;
    [SerializeField] private string extraPassivePink;
    [SerializeField] private GameObject passivePrefabPink;
    [SerializeField] private SoundType[] passiveSoundPink;
    [SerializeField] private float passivePowerModifierPink = 0f;
    [SerializeField] private float passiveRateModifierPink = 0f;
    [SerializeField] private float passiveRangeModifierPink = 0f;
    [SerializeField] private float passivePierceModifierPink = 0f;
    [SerializeField] private float passiveDurationPink = 0f;
    [SerializeField] private float passiveExtraModifierPink = 0f;

    //trackers
    private Attributes attributes;

    private void Awake()
    {
        attributes = gameObject.GetComponent<Attributes>();
    }
    
    private void Start()
    {
        
    }

    public void SetPrestigeStats()
    {

    }
}
